# Generated by `clinix env flake <target> wrap-shell`. Wraps an existing shell.nix
# that takes a `pkgs` argument (a conventional `{ pkgs ? ... }:` dev shell). clinix
# pins nixpkgs below and passes `pkgs` in, so `nix develop` is reproducible without
# <nixpkgs>/channels. The pin is recorded in the sibling flake.lock (clinix-owned,
# written classically — no `nix flake`).
{
  description = "Dev shell (flake wrapper around ./shell.nix)";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs =
    { self, nixpkgs }:
    let
      lib = nixpkgs.lib;
      systems = [ "x86_64-linux" "aarch64-linux" ];
    in
    {
      devShells = lib.genAttrs systems (system: {
        default = import ./shell.nix { pkgs = import nixpkgs { inherit system; }; };
      });
      legacyPackages = lib.genAttrs systems (system: import nixpkgs { inherit system; });
    };
}
