# Generated by `clinix env flake <target> wrap-shell --impure`.
#
# WARNING: NOT reproducible. The wrapped shell.nix takes no injectable `pkgs`
# (no formal arguments, a positional argument, or a top-level `import <nixpkgs>`),
# so it cannot be evaluated under pure flake eval. It runs against the ambient
# channel and MUST be entered with:
#
#     nix develop --impure
#
# To make it reproducible, convert shell.nix to a `{ pkgs ? ... }:` function and
# re-run `clinix env flake <target> wrap-shell` (drop --impure). No nixpkgs input
# is declared here, so there is nothing to lock — hence no flake.lock.
{
  description = "IMPURE flake wrapper around ./shell.nix — run `nix develop --impure`";

  outputs =
    { self }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
      forAll =
        f:
        builtins.listToAttrs (
          map (system: {
            name = system;
            value = f system;
          }) systems
        );
    in
    {
      devShells = forAll (system: {
        default = import ./shell.nix { };
      });
    };
}
